"""empty message

Revision ID: 80062d545586
Revises: 80d14df212a6
Create Date: 2021-01-22 17:48:34.662306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80062d545586'
down_revision = '80d14df212a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('CREATION_DATE', sa.DateTime(), nullable=False),
    sa.Column('LAST_MODIFICATION_DATE', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
